### ISSUE TITLE
排序计划执行无结果

### ISSUE THREAD

**Issue by git208** [stocksdktest/IOSTestRunner#5]
http://221.228.66.83:30690/admin/airflow/graph?base_date=2020-09-14+08%3A52%3A26&num_runs=25&execution_date=2020-09-14T03%3A00%3A56%2B00%3A00&arrange=LR&root=&dag_id=ios_sort&_csrf_token=ImI3YzZlYTIzMTRmNjAyMGQxNTQyYWZmYjJkMjQ3NzBmZTUxNmMwZjYi.X3Eo8Q.3getQh6y5wAK_Fx5ChtuPDQkUtA

**Comment by Tsunaou** [comment]
原因描述：
- 传参的时候把collectionName写成了Test_Android_quote_20200316，但是iOSTestRunner里的MongoDB API不适配，只能是通过restful服务访问数据库，把结果存在test_result里，所以一直没有结果。

解决方法：
- IOS的collectionName **只能是** test_result 。安卓无此限制。
