### ISSUE TITLE
某段时间内会频繁出现报错现象

### ISSUE THREAD

**Issue by git208** [stocksdktest/IOSTestRunner#6]
报错日志：
http://221.228.66.83:30690/admin/airflow/log?task_id=ios_cmp_b&dag_id=ios_compare1&execution_date=2020-09-22T07%3A09%3A18%2B00%3A00&format=json

**Comment by yuping-nju** [comment]
虚拟机重启后再试的结果如何？

**Comment by git208** [comment]
虚拟机重启后测试暂未发现该问题
