### ISSUE TITLE
存在执行时程序调用失败，近期较为频繁

### ISSUE THREAD

**Issue by git208** [stocksdktest/IOSTestRunner#7]
http://221.228.66.83:30690/admin/airflow/log?task_id=ios_cmp_a&dag_id=ios_compare3&execution_date=2020-09-21T07%3A00%3A44%2B00%3A00&format=json
http://221.228.66.83:30690/admin/airflow/log?task_id=ios_cmp_a&dag_id=ios_compare3&execution_date=2020-09-21T05%3A53%3A07%2B00%3A00&format=json
http://221.228.66.83:30690/admin/airflow/log?task_id=ios_cmp_a&dag_id=ios_compare3&execution_date=2020-09-21T06%3A52%3A56%2B00%3A00&format=json
http://221.228.66.83:30690/admin/airflow/log?task_id=ios_cmp_b&dag_id=ios_compare1&execution_date=2020-09-21T07%3A21%3A05%2B00%3A00&format=json

**Comment by yuping-nju** [comment]
虚拟机重启后再试的结果如何？

**Comment by git208** [comment]
虚拟机重启后测试暂未发现该问题
